import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const root = fileURLToPath(new URL("../", import.meta.url));
const backend = resolve(root, "../backend");
const output = resolve(root, "src/api/schema.d.ts");
const python = process.env.SEOKPAN_API_PYTHON ?? resolve(
  backend, process.platform === "win32" ? ".venv/Scripts/python.exe" : ".venv/bin/python",
);
let schemaPath;
let check = false;
const args = process.argv.slice(2);
for (let index = 0; index < args.length; index += 1) {
  if (args[index] === "--check") check = true;
  else if (args[index] === "--schema" && args[index + 1] && !args[index + 1].startsWith("--")) {
    schemaPath = resolve(args[++index]);
  } else {
    throw new Error("Usage: node scripts/generate-api.mjs [--check] [--schema local-file.json]");
  }
}
// CI may export JSON in the Python container, then check it in the Node container.
// The caller must supply a fresh export from this same checkout, not a remote URL.
const raw = schemaPath ? readFileSync(schemaPath, "utf8") : execFileSync(python, ["scripts/export_openapi.py"], {
  cwd: backend,
  encoding: "utf8",
  maxBuffer: 8 * 1024 * 1024,
  timeout: 30_000,
  env: { ...process.env, PYTHONDONTWRITEBYTECODE: "1", PYTHONIOENCODING: "utf-8" },
});
const schema = JSON.parse(raw.replace(/^\uFEFF/, ""));
const content = "// Generated by npm run api:generate. Do not edit manually.\n"
  + astToString(await openapiTS(schema, { alphabetize: true }));
if (check) {
  // Normalize checkout line endings only. Every schema change must still fail.
  if (!existsSync(output) || readFileSync(output, "utf8").replace(/\r\n/g, "\n") !== content) {
    console.error("API types differ from Backend OpenAPI. Run npm run api:generate and review the diff.");
    process.exitCode = 1;
  } else {
    console.log("Backend OpenAPI and generated API types match.");
  }
} else {
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, content);
  console.log("Generated src/api/schema.d.ts from the local Backend.");
}
